[package]
name = "wave_wars"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
rand = "0.8"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "wave_wars"
path = "src/main.rs"
